In [11]:
# task 4.1 Q1
import numpy as np
empty_array = np.zeros((3, 3))
print(empty_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# task Q2
import numpy as np
one_array = np.ones((4, 2))
print(one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
# Q3
import numpy as np
my_array = np.full((2, 3), 9)
print(my_array)

[[9 9 9]
 [9 9 9]]


In [23]:
# Q4
original_array = np.array([[1, 2, 3], [4, 5, 6]])
print("This is original array:")
print(original_array)

# now using zeros_like to create a new but in previous matrix
my_array = np.zeros_like(original_array)
print("\nThis is new array:")
print(my_array)

This is original array:
[[1 2 3]
 [4 5 6]]

This is new array:
[[0 0 0]
 [0 0 0]]


In [25]:
# Q5
import numpy as np
initial_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Initial array:")
print(initial_array)

# now using np.ones_like to create a new but same shape and type before
new_array = np.ones_like(initial_array)
print("\nAfter New Array:")
print(new_array)


Initial array:
[[1 2 3]
 [4 5 6]]

After New Array:
[[1 1 1]
 [1 1 1]]


In [34]:
import numpy as np

# Defining the existing list
new_list = [1, 2, 3, 4]
print("Original list:", new_list)

# Convert to numpy array
convert_array = np.array(new_list)
print("Numpy array:", convert_array)

Original list: [1, 2, 3, 4]
Numpy array: [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [48]:
# Q1
import numpy as np
new_array = np.arange(10, 50)
print("An array with values ranging from 10 to 49. \n")
print(new_array)
#

An array with values ranging from 10 to 49. 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [50]:
# Q2
import numpy as np
my_array = np.arange(0,9).reshape(3,3)
print("A 3X3 matrix with values ranging from 0 to 8.\n")
print(my_array)


A 3X3 matrix with values ranging from 0 to 8.

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [59]:
# Q3
import numpy as np
my_array = np.eye(3)
print("A 3X3 identity matrix.\n")
print(my_array)


A 3X3 identity matrix.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
# Q4
import numpy as np
random_array = np.random.rand(30)
print("A 1-D array with 30 random values between 0 and 1.\n")
print(random_array)

mean_array = np.mean(random_array)
print("\nThe mean of the array is: ", mean_array)

A 1-D array with 30 random values between 0 and 1.

[0.67685057 0.18634933 0.17581952 0.03645715 0.09253719 0.66403362
 0.86131489 0.18525491 0.08765011 0.06736438 0.61725382 0.47906442
 0.36292155 0.33190266 0.96470734 0.58484264 0.78685313 0.36253734
 0.77587556 0.61578028 0.18935327 0.01420889 0.46915719 0.61468335
 0.41681977 0.31075373 0.14301496 0.7421826  0.10583442 0.18816946]

The mean of the array is:  0.40365160212151024


In [70]:
# Q5
import numpy as np
import numpy as np

# Create a 10x10 array with random values between 0 and 1
random_array = np.random.random((10, 10))
print("10x10 Random Array:")
print(random_array)

# Find minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print(f"\nMinimum value: {min_value}")
print(f"Maximum value: {max_value}")



10x10 Random Array:
[[0.07863294 0.20718568 0.54309163 0.93081238 0.02090162 0.47658382
  0.15189025 0.51722656 0.80511497 0.2137503 ]
 [0.35509902 0.50074458 0.4217574  0.85082282 0.6124123  0.09807401
  0.79462904 0.39121347 0.32423105 0.73138707]
 [0.99891419 0.22525784 0.74348676 0.05532222 0.54870471 0.91478254
  0.2546043  0.74703855 0.46098154 0.9156285 ]
 [0.24917867 0.70249854 0.93869112 0.6647418  0.75795432 0.31376193
  0.58288213 0.60674432 0.65801094 0.62421711]
 [0.98440043 0.52311765 0.17208909 0.27129495 0.44949963 0.06948992
  0.11966084 0.37291359 0.23004996 0.66152324]
 [0.11101799 0.26173014 0.49962601 0.38648184 0.55346403 0.18720389
  0.93329685 0.00229393 0.89367882 0.03672528]
 [0.07560249 0.35969027 0.67059313 0.35206475 0.14878626 0.83477491
  0.46032871 0.85013037 0.2805622  0.20702626]
 [0.06343823 0.07535568 0.57233787 0.65429311 0.35101107 0.15949428
  0.5152554  0.7134001  0.4832511  0.47928792]
 [0.48265512 0.96407661 0.2478941  0.78859252 0.25411184 0.9

In [81]:
# Q6
import numpy as np
zero_array = np.zeros(10) #creating a zero array of size 10.
print("A zero array of size 10. ")
print(zero_array)

zero_array[5] = 1 # replacing 5th element with 1
print("\nA zero array of size 10 and replace 5th element with 1.")
print(zero_array)


A zero array of size 10. 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

A zero array of size 10 and replace 5th element with 1.
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [90]:
# Q7

arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1] #reverse the array using slicing method [::-1]

print("\nOriginal array:\n", arr)
print("\nReversed array:\n", reversed_arr)



Original array:
 [1, 2, 0, 0, 4, 0]

Reversed array:
 [0, 4, 0, 0, 2, 1]


In [99]:
# Q8
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [109]:
# Q9
import numpy as np

# Create an 8x8 array of zeros
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("8x8 Checkerboard Pattern:\n")
print(checkerboard)

8x8 Checkerboard Pattern:

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:


In [117]:
import numpy as np

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Original arrays:")
print("x =\n", x)
print("y =\n", y)
print("v =", v)
print("w =", w)

# Task 1: Add arrays
add_xy = x + y
print("\n1. x + y:")
print(add_xy)

# Task 2: Subtract arrays
sub_xy = x - y
print("\n2. x - y:")
print(sub_xy)

# Task 3: Multiply with integer
mult_x = x * 3
mult_y = y * 2
print("\n3. x * 3:")
print(mult_x)
print("y * 2:")
print(mult_y)

# Task 4: Square of each element
square_x = x ** 2
square_y = y ** 2
print("\n4. Square of x:")
print(square_x)
print("Square of y:")
print(square_y)

# Task 5: Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\n5. Dot products:")
print("v · w =", dot_vw)
print("x · v =", dot_xv)
print("x · y =\n", dot_xy)

# Task 6: Concatenation
concat_row = np.concatenate((x, y), axis=0)  # Along rows
concat_col_vw = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)  # Along columns

# Alternative using vstack and hstack
concat_row_alt = np.vstack((x, y))
concat_col_alt = np.column_stack((v, w))

print("\n6. Concatenation:")
print("x and y along rows:\n", concat_row)
print("v and w along columns:\n", concat_col_vw)

# Task 7: Concatenate x and v (will cause error)
print("\n7. Concatenate x and v:")
try:
    concat_xv = np.concatenate((x, v))
    print("Success:", concat_xv)
except ValueError as e:
    print("Error:", e)
    print("Explanation: Cannot concatenate arrays with different dimensions.")
    print("x shape:", x.shape, "(2D array)")
    print("v shape:", v.shape, "(1D array)")
    print("All input arrays must have the same number of dimensions for concatenation.")

Original arrays:
x =
 [[1 2]
 [3 5]]
y =
 [[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

1. x + y:
[[ 6  8]
 [10 13]]

2. x - y:
[[-4 -4]
 [-4 -3]]

3. x * 3:
[[ 3  6]
 [ 9 15]]
y * 2:
[[10 12]
 [14 16]]

4. Square of x:
[[ 1  4]
 [ 9 25]]
Square of y:
[[25 36]
 [49 64]]

5. Dot products:
v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]

6. Concatenation:
x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along columns:
 [[ 9 11]
 [10 12]]

7. Concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Cannot concatenate arrays with different dimensions.
x shape: (2, 2) (2D array)
v shape: (2,) (1D array)
All input arrays must have the same number of dimensions for concatenation.


Problem - 4: Matrix Operations:

In [121]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("Original matrices:")
print("A =\n", A)
print("B =\n", B)

print("\n" + "="*50)
print("1. Prove A × A⁻¹ = I")
print("="*50)

# Calculate inverse of A
try:
    A_inv = np.linalg.inv(A)
    print("A⁻¹ =\n", A_inv)

    # Multiply A and A inverse
    product = np.dot(A, A_inv)
    print("\nA × A⁻¹ =\n", product)

    # Create identity matrix for comparison
    I = np.eye(2)
    print("\nIdentity matrix I =\n", I)

    # Check if they are equal (considering floating point precision)
    are_equal = np.allclose(product, I)
    print(f"\nA × A⁻¹ = I: {are_equal}")

except np.linalg.LinAlgError:
    print("Matrix A is singular, cannot compute inverse")

print("\n" + "="*50)
print("2. Prove AB ≠ BA")
print("="*50)

# Calculate AB
AB = np.dot(A, B)
print("AB =\n", AB)

# Calculate BA
BA = np.dot(B, A)
print("\nBA =\n", BA)

# Check if they are equal
are_equal = np.array_equal(AB, BA)
print(f"\nAB = BA: {are_equal}")
print(f"Therefore, AB ≠ BA: {not are_equal}")

# Show the difference
difference = AB - BA
print(f"\nDifference (AB - BA) =\n", difference)

print("\n" + "="*50)
print("3. Prove (AB)ᵀ = BᵀAᵀ")
print("="*50)

# Calculate (AB)ᵀ
AB_transpose = AB.T
print("(AB)ᵀ =\n", AB_transpose)

# Calculate BᵀAᵀ
B_transpose = B.T
A_transpose = A.T
BTA_transpose = np.dot(B_transpose, A_transpose)
print("\nBᵀAᵀ =\n", BTA_transpose)

# Check if they are equal
are_equal = np.array_equal(AB_transpose, BTA_transpose)
print(f"\n(AB)ᵀ = BᵀAᵀ: {are_equal}")

# Show they are identical
print(f"\nAre the matrices identical? {np.array_equal(AB_transpose, BTA_transpose)}")

Original matrices:
A =
 [[3 4]
 [7 8]]
B =
 [[5 3]
 [2 1]]

1. Prove A × A⁻¹ = I
A⁻¹ =
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A × A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix I =
 [[1. 0.]
 [0. 1.]]

A × A⁻¹ = I: True

2. Prove AB ≠ BA
AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

AB = BA: False
Therefore, AB ≠ BA: True

Difference (AB - BA) =
 [[-13 -31]
 [ 38  13]]

3. Prove (AB)ᵀ = BᵀAᵀ
(AB)ᵀ =
 [[23 51]
 [13 29]]

BᵀAᵀ =
 [[23 51]
 [13 29]]

(AB)ᵀ = BᵀAᵀ: True

Are the matrices identical? True


In [142]:
import numpy as np

print("Solving System of Linear Equations using Inverse Method")
print("_" * 55)
print("Equations:")
print("2x - 3y +  z = -1")
print(" x -  y + 2z = -3")
print("3x +  y -  z =  9")

# Step 1: Matrix representation
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([[-1],
              [-3],
              [9]])

print("\nStep 1: Matrix Representation")
print("A =")
print(A)
print("\nB =")
print(B)

# Step 2: Check invertibility
print("\nStep 2: Check Invertibility")
det_A = np.linalg.det(A)
print(f"det(A) = {det_A:.2f}")

if abs(det_A) < 1e-10:
    print("Matrix is singular. Cannot use inverse method.")
else:
    print("Matrix is invertible. Proceeding with inverse method.")

    # Step 3: Find inverse
    print("\nStep 3: Find Inverse of A")
    A_inv = np.linalg.inv(A)
    print("A⁻¹ =")
    print(A_inv)

    # Step 4: Solve X = A⁻¹B
    print("\nStep 4: Solve X = A⁻¹B")
    X = np.dot(A_inv, B)
    print("X =")
    print(X)

    x, y, z = X.flatten()
    print(f"\nFinal Solution:")
    print(f"x = {x:.2f}")
    print(f"y = {y:.2f}")
    print(f"z = {z:.2f}")

    # Step 5: Verification
    print("\nStep 5: Verification")
    eq1 = 2*x - 3*y + z
    eq2 = x - y + 2*z
    eq3 = 3*x + y - z

    print(f"Equation 1: 2({x:.2f}) - 3({y:.2f}) + ({z:.2f}) = {eq1:.2f}")
    print(f"Equation 2: {x:.2f} - {y:.2f} + 2({z:.2f}) = {eq2:.2f}")
    print(f"Equation 3: 3({x:.2f}) + {y:.2f} - {z:.2f}) = {eq3:.2f}")

    if np.allclose([eq1, eq2, eq3], [-1, -3, 9]):
        print("\n✓ Solution verified successfully!")
    else:
        print("\n✗ Solution verification failed!")

# Alternative: Using np.linalg.solve() for comparison
print("\n" + "_"*55)
print("Alternative: Using np.linalg.solve()")
X_alt = np.linalg.solve(A, B)
x_alt, y_alt, z_alt = X_alt.flatten()
print(f"x = {x_alt:.2f}, y = {y_alt:.2f}, z = {z_alt:.2f}")

Solving System of Linear Equations using Inverse Method
_______________________________________________________
Equations:
2x - 3y +  z = -1
 x -  y + 2z = -3
3x +  y -  z =  9

Step 1: Matrix Representation
A =
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

B =
[[-1]
 [-3]
 [ 9]]

Step 2: Check Invertibility
det(A) = -19.00
Matrix is invertible. Proceeding with inverse method.

Step 3: Find Inverse of A
A⁻¹ =
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Step 4: Solve X = A⁻¹B
X =
[[ 2.]
 [ 1.]
 [-2.]]

Final Solution:
x = 2.00
y = 1.00
z = -2.00

Step 5: Verification
Equation 1: 2(2.00) - 3(1.00) + (-2.00) = -1.00
Equation 2: 2.00 - 1.00 + 2(-2.00) = -3.00
Equation 3: 3(2.00) + 1.00 - -2.00) = 9.00

✓ Solution verified successfully!

_______________________________________________________
Alternative: Using np.linalg.solve()
x = 2.00, y = 1.00, z = -2.00


In [146]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([[-1],
              [-3],
              [9]])

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

x = X[0][0]
y = X[1][0]
z = X[2][0]

print("Solution:")
print("x =", x)
print("y =", y)
print("z =", z)

print("Verification:")
print("Equation 1: 2*x - 3*y + z =", 2*x - 3*y + z)
print("Equation 2: x - y + 2*z =", x - y + 2*z)
print("Equation 3: 3*x + y - z =", 3*x + y - z)

Matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Matrix B:
[[-1]
 [-3]
 [ 9]]
Solution:
x = 2.0
y = 1.0
z = -2.0
Verification:
Equation 1: 2*x - 3*y + z = -1.0
Equation 2: x - y + 2*z = -3.0
Equation 3: 3*x + y - z = 9.0


4.2 Experiment: How Fast is Numpy?

In [148]:
import numpy as np
import time

# Set the sizes
list_size = 1000000
matrix_size = 1000

print("NUMPY VS PYTHON LISTS PERFORMANCE COMPARISON")
print("=" * 50)

# 1. ELEMENT-WISE ADDITION
print("\n1. ELEMENT-WISE ADDITION")

# Python Lists
python_list1 = list(range(list_size))
python_list2 = list(range(list_size, list_size * 2))

start_time = time.time()
result_python_add = [python_list1[i] + python_list2[i] for i in range(list_size)]
python_add_time = time.time() - start_time
print(f"Python Lists Time: {python_add_time:.6f} seconds")

# NumPy Arrays
numpy_array1 = np.arange(list_size)
numpy_array2 = np.arange(list_size, list_size * 2)

start_time = time.time()
result_numpy_add = numpy_array1 + numpy_array2
numpy_add_time = time.time() - start_time
print(f"NumPy Arrays Time: {numpy_add_time:.6f} seconds")
print(f"Speedup: {python_add_time/numpy_add_time:.2f}x")

# 2. ELEMENT-WISE MULTIPLICATION
print("\n2. ELEMENT-WISE MULTIPLICATION")

# Python Lists
start_time = time.time()
result_python_mul = [python_list1[i] * python_list2[i] for i in range(list_size)]
python_mul_time = time.time() - start_time
print(f"Python Lists Time: {python_mul_time:.6f} seconds")

# NumPy Arrays
start_time = time.time()
result_numpy_mul = numpy_array1 * numpy_array2
numpy_mul_time = time.time() - start_time
print(f"NumPy Arrays Time: {numpy_mul_time:.6f} seconds")
print(f"Speedup: {python_mul_time/numpy_mul_time:.2f}x")

# 3. DOT PRODUCT
print("\n3. DOT PRODUCT")

# Python Lists
start_time = time.time()
dot_python = sum(python_list1[i] * python_list2[i] for i in range(list_size))
python_dot_time = time.time() - start_time
print(f"Python Lists Time: {python_dot_time:.6f} seconds")

# NumPy Arrays
start_time = time.time()
dot_numpy = np.dot(numpy_array1, numpy_array2)
numpy_dot_time = time.time() - start_time
print(f"NumPy Arrays Time: {numpy_dot_time:.6f} seconds")
print(f"Speedup: {python_dot_time/numpy_dot_time:.2f}x")

# 4. MATRIX MULTIPLICATION
print("\n4. MATRIX MULTIPLICATION")

# Python Lists (as nested lists)
python_matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
python_matrix2 = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]

start_time = time.time()
result_python_matmul = [[0 for _ in range(matrix_size)] for _ in range(matrix_size)]
for i in range(matrix_size):
    for j in range(matrix_size):
        for k in range(matrix_size):
            result_python_matmul[i][j] += python_matrix1[i][k] * python_matrix2[k][j]
python_matmul_time = time.time() - start_time
print(f"Python Lists Time: {python_matmul_time:.6f} seconds")

# NumPy Arrays
numpy_matrix1 = np.array(python_matrix1)
numpy_matrix2 = np.array(python_matrix2)

start_time = time.time()
result_numpy_matmul = np.matmul(numpy_matrix1, numpy_matrix2)
numpy_matmul_time = time.time() - start_time
print(f"NumPy Arrays Time: {numpy_matmul_time:.6f} seconds")
print(f"Speedup: {python_matmul_time/numpy_matmul_time:.2f}x")

# SUMMARY
print("\n" + "=" * 50)
print("PERFORMANCE SUMMARY")
print("=" * 50)
print(f"{'Operation':<25} {'Python Time':<12} {'NumPy Time':<12} {'Speedup':<10}")
print("-" * 50)
print(f"{'Element-wise Addition':<25} {python_add_time:<12.6f} {numpy_add_time:<12.6f} {python_add_time/numpy_add_time:<10.2f}x")
print(f"{'Element-wise Multiplication':<25} {python_mul_time:<12.6f} {numpy_mul_time:<12.6f} {python_mul_time/numpy_mul_time:<10.2f}x")
print(f"{'Dot Product':<25} {python_dot_time:<12.6f} {numpy_dot_time:<12.6f} {python_dot_time/numpy_dot_time:<10.2f}x")
print(f"{'Matrix Multiplication':<25} {python_matmul_time:<12.6f} {numpy_matmul_time:<12.6f} {python_matmul_time/numpy_matmul_time:<10.2f}x")

NUMPY VS PYTHON LISTS PERFORMANCE COMPARISON

1. ELEMENT-WISE ADDITION
Python Lists Time: 0.122936 seconds
NumPy Arrays Time: 0.005322 seconds
Speedup: 23.10x

2. ELEMENT-WISE MULTIPLICATION
Python Lists Time: 0.124602 seconds
NumPy Arrays Time: 0.005082 seconds
Speedup: 24.52x

3. DOT PRODUCT
Python Lists Time: 0.103457 seconds
NumPy Arrays Time: 0.001936 seconds
Speedup: 53.43x

4. MATRIX MULTIPLICATION


KeyboardInterrupt: 